-- auto Generated on 2019-08-30 21:47:44 
-- DROP TABLE IF EXISTS `v_auth`; 
CREATE TABLE `v_auth`(
    `name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'name',
    `type` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'type',
    `url` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'url',
    `info` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'info',
    `id` BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT 'id',
    `is_del` SMALLINT (5) NOT NULL DEFAULT 0 COMMENT 'isDel',
    `create_time` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'createTime',
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updateTime',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '`v_auth`';
