-- auto Generated on 2019-07-14 15:57:07 
-- DROP TABLE IF EXISTS `user`; 
CREATE TABLE `user`(
    `user_name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'userName',
    `pass_word` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'passWord',
    `email` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'email',
    `id` BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT 'id',
    `create_time` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'createTime',
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updateTime',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '`user`';
